#!/bin/sh
set -e

. /usr/share/debconf/confmodule

case "$1" in
    purge)
        deluser --system --quiet vaulthalla || true
        rm -rf /mnt/vaulthalla /var/lib/vaulthalla /var/log/vaulthalla

        # purge the debconf
        echo "Purging debconf settings for vaulthalla..."
        db_purge || true
        ;;
esac

exit 0
