#!/bin/sh
set -e

case "$1" in
    purge)
        deluser --system --quiet vaulthalla || true
        rm -rf /mnt/vaulthalla /var/lib/vaulthalla /var/log/vaulthalla

        # purge the debconf
        echo "Purging debconf settings..."
        db_purge vaulthalla/init-db || true
        ;;
esac

exit 0
