name: 'Build Web'
description: 'Builds the web frontend.'

runs:
  using: "composite"
  steps:
    - name: Build web
      shell: bash
      working-directory: ${{ github.workspace }}/web
      run: pnpm build
